//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ApplicationProgramChannel_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationProgramChannel_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ParameterBlock" type="{http://knx.org/xml/project/20}ComObjectParameterBlock_t"/>
 *         &lt;element name="ComObjectRefRef" type="{http://knx.org/xml/project/20}ComObjectRefRef_t"/>
 *         &lt;element name="BinaryDataRef" type="{http://knx.org/xml/project/20}BinaryDataRef_t"/>
 *         &lt;element name="Module" type="{http://knx.org/xml/project/20}Module_t"/>
 *         &lt;element name="Repeat" type="{http://knx.org/xml/project/20}Repeat_t"/>
 *         &lt;element name="choose" type="{http://knx.org/xml/project/20}ChannelChoose_t"/>
 *       &lt;/choice>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="Name" use="required" type="{http://knx.org/xml/project/20}String255_t" />
 *       &lt;attribute name="Text" type="{http://knx.org/xml/project/20}LanguageDependentString255_t" />
 *       &lt;attribute name="Number" use="required" type="{http://knx.org/xml/project/20}String50_t" />
 *       &lt;attribute name="TextParameterRefId" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="InternalDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Icon" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HelpContext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Semantics" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationProgramChannel_t", propOrder = {
    "parameterBlockOrComObjectRefRefOrBinaryDataRef"
})
public class ApplicationProgramChannelT {

    @XmlElements({
        @XmlElement(name = "ParameterBlock", type = ComObjectParameterBlockT.class),
        @XmlElement(name = "ComObjectRefRef", type = ComObjectRefRefT.class),
        @XmlElement(name = "BinaryDataRef", type = BinaryDataRefT.class),
        @XmlElement(name = "Module", type = ModuleT.class),
        @XmlElement(name = "Repeat", type = RepeatT.class),
        @XmlElement(name = "choose", type = ChannelChooseT.class)
    })
    protected List<Object> parameterBlockOrComObjectRefRefOrBinaryDataRef;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Text")
    protected String text;
    @XmlAttribute(name = "Number", required = true)
    protected String number;
    @XmlAttribute(name = "TextParameterRefId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textParameterRefId;
    @XmlAttribute(name = "InternalDescription")
    protected String internalDescription;
    @XmlAttribute(name = "Icon")
    protected String icon;
    @XmlAttribute(name = "HelpContext")
    protected String helpContext;
    @XmlAttribute(name = "Semantics")
    protected String semantics;

    /**
     * Gets the value of the parameterBlockOrComObjectRefRefOrBinaryDataRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterBlockOrComObjectRefRefOrBinaryDataRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterBlockOrComObjectRefRefOrBinaryDataRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComObjectParameterBlockT }
     * {@link ComObjectRefRefT }
     * {@link BinaryDataRefT }
     * {@link ModuleT }
     * {@link RepeatT }
     * {@link ChannelChooseT }
     * 
     * 
     */
    public List<Object> getParameterBlockOrComObjectRefRefOrBinaryDataRef() {
        if (parameterBlockOrComObjectRefRefOrBinaryDataRef == null) {
            parameterBlockOrComObjectRefRefOrBinaryDataRef = new ArrayList<Object>();
        }
        return this.parameterBlockOrComObjectRefRefOrBinaryDataRef;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the textParameterRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextParameterRefId() {
        return textParameterRefId;
    }

    /**
     * Sets the value of the textParameterRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextParameterRefId(String value) {
        this.textParameterRefId = value;
    }

    /**
     * Gets the value of the internalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalDescription() {
        return internalDescription;
    }

    /**
     * Sets the value of the internalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalDescription(String value) {
        this.internalDescription = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the helpContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpContext() {
        return helpContext;
    }

    /**
     * Sets the value of the helpContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpContext(String value) {
        this.helpContext = value;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemantics() {
        return semantics;
    }

    /**
     * Sets the value of the semantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemantics(String value) {
        this.semantics = value;
    }

}
