//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ComObjectInstanceRef_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComObjectInstanceRef_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="RefId" use="required" type="{http://knx.org/xml/project/20}RELIDREF" />
 *       &lt;attribute name="Text" type="{http://knx.org/xml/project/20}String255_t" />
 *       &lt;attribute name="FunctionText" type="{http://knx.org/xml/project/20}String255_t" />
 *       &lt;attribute name="Priority" type="{http://knx.org/xml/project/20}ComObjectPriority_t" />
 *       &lt;attribute name="ReadFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="WriteFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="CommunicationFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="TransmitFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="UpdateFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="ReadOnInitFlag" type="{http://knx.org/xml/project/20}Enable_t" />
 *       &lt;attribute name="DatapointType" type="{http://knx.org/xml/project/20}IDREFS" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ChannelId" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="Links" type="{http://knx.org/xml/project/20}RELIDREFS" />
 *       &lt;attribute name="Acknowledges" type="{http://knx.org/xml/project/20}RELIDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComObjectInstanceRef_t")
public class ComObjectInstanceRefT {

    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "RefId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refId;
    @XmlAttribute(name = "Text")
    protected String text;
    @XmlAttribute(name = "FunctionText")
    protected String functionText;
    @XmlAttribute(name = "Priority")
    protected ComObjectPriorityT priority;
    @XmlAttribute(name = "ReadFlag")
    protected EnableT readFlag;
    @XmlAttribute(name = "WriteFlag")
    protected EnableT writeFlag;
    @XmlAttribute(name = "CommunicationFlag")
    protected EnableT communicationFlag;
    @XmlAttribute(name = "TransmitFlag")
    protected EnableT transmitFlag;
    @XmlAttribute(name = "UpdateFlag")
    protected EnableT updateFlag;
    @XmlAttribute(name = "ReadOnInitFlag")
    protected EnableT readOnInitFlag;
    @XmlAttribute(name = "DatapointType")
    protected List<String> datapointType;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "ChannelId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String channelId;
    @XmlAttribute(name = "Links")
    protected List<String> links;
    @XmlAttribute(name = "Acknowledges")
    protected List<String> acknowledges;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the functionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionText() {
        return functionText;
    }

    /**
     * Sets the value of the functionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionText(String value) {
        this.functionText = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link ComObjectPriorityT }
     *     
     */
    public ComObjectPriorityT getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComObjectPriorityT }
     *     
     */
    public void setPriority(ComObjectPriorityT value) {
        this.priority = value;
    }

    /**
     * Gets the value of the readFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getReadFlag() {
        return readFlag;
    }

    /**
     * Sets the value of the readFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setReadFlag(EnableT value) {
        this.readFlag = value;
    }

    /**
     * Gets the value of the writeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getWriteFlag() {
        return writeFlag;
    }

    /**
     * Sets the value of the writeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setWriteFlag(EnableT value) {
        this.writeFlag = value;
    }

    /**
     * Gets the value of the communicationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getCommunicationFlag() {
        return communicationFlag;
    }

    /**
     * Sets the value of the communicationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setCommunicationFlag(EnableT value) {
        this.communicationFlag = value;
    }

    /**
     * Gets the value of the transmitFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getTransmitFlag() {
        return transmitFlag;
    }

    /**
     * Sets the value of the transmitFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setTransmitFlag(EnableT value) {
        this.transmitFlag = value;
    }

    /**
     * Gets the value of the updateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getUpdateFlag() {
        return updateFlag;
    }

    /**
     * Sets the value of the updateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setUpdateFlag(EnableT value) {
        this.updateFlag = value;
    }

    /**
     * Gets the value of the readOnInitFlag property.
     * 
     * @return
     *     possible object is
     *     {@link EnableT }
     *     
     */
    public EnableT getReadOnInitFlag() {
        return readOnInitFlag;
    }

    /**
     * Sets the value of the readOnInitFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnableT }
     *     
     */
    public void setReadOnInitFlag(EnableT value) {
        this.readOnInitFlag = value;
    }

    /**
     * Gets the value of the datapointType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datapointType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatapointType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDatapointType() {
        if (datapointType == null) {
            datapointType = new ArrayList<String>();
        }
        return this.datapointType;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelId(String value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLinks() {
        if (links == null) {
            links = new ArrayList<String>();
        }
        return this.links;
    }

    /**
     * Gets the value of the acknowledges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acknowledges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcknowledges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAcknowledges() {
        if (acknowledges == null) {
            acknowledges = new ArrayList<String>();
        }
        return this.acknowledges;
    }

}
