//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeviceInstance_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceInstance_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParameterInstanceRefs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ParameterInstanceRef" type="{http://knx.org/xml/project/20}ParameterInstanceRef_t" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ComObjectInstanceRefs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ComObjectInstanceRef" type="{http://knx.org/xml/project/20}ComObjectInstanceRef_t" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ChannelInstances" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ChannelInstance" type="{http://knx.org/xml/project/20}ChannelInstance_t" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ModuleInstances" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ModuleInstance" type="{http://knx.org/xml/project/20}ModuleInstance_t" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GroupObjectTree" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nodes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Node" type="{http://knx.org/xml/project/20}Node_t" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="GroupObjectInstances" type="{http://knx.org/xml/project/20}RELIDREFS" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalAddresses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Address" maxOccurs="254">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Address" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *                                 &lt;minInclusive value="1"/>
 *                                 &lt;maxInclusive value="255"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
 *                           &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BinaryData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BinaryData" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="RefId" type="{http://knx.org/xml/project/20}IDREF" />
 *                           &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
 *                           &lt;attribute name="AutoCopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IPConfig" type="{http://knx.org/xml/project/20}IPConfig_t" minOccurs="0"/>
 *         &lt;element name="Security" type="{http://knx.org/xml/project/20}Security_t" minOccurs="0"/>
 *         &lt;element name="BusInterfaces" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BusInterface" type="{http://knx.org/xml/project/20}BusInterface_t" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RfFastAckSlots" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Slot" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="GroupAddressRefId" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *                           &lt;attribute name="Number" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *                                 &lt;maxInclusive value="63"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="ProductRefId" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="Hardware2ProgramRefId" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="Address">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="LastDownload" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="LastUsedAPDULength" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="ReadMaxAPDULength" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="ReadMaxRoutingAPDULength" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="InstallationHints" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CompletionStatus" type="{http://knx.org/xml/project/20}CompletionStatus_t" default="Undefined" />
 *       &lt;attribute name="IndividualAddressLoaded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ApplicationProgramLoaded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ParametersLoaded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="CommunicationPartLoaded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="MediumConfigLoaded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="LoadedImage" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CheckSums" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="DownloadCounter" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="IsActivityCalculated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Broken" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="UniqueId" type="{http://knx.org/xml/project/20}Guid_t" />
 *       &lt;attribute name="IsRFRetransmitter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Puid" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceInstance_t", propOrder = {
    "parameterInstanceRefs",
    "comObjectInstanceRefs",
    "channelInstances",
    "moduleInstances",
    "groupObjectTree",
    "additionalAddresses",
    "binaryData",
    "ipConfig",
    "security",
    "busInterfaces",
    "rfFastAckSlots"
})
public class DeviceInstanceT {

    @XmlElement(name = "ParameterInstanceRefs")
    protected DeviceInstanceT.ParameterInstanceRefs parameterInstanceRefs;
    @XmlElement(name = "ComObjectInstanceRefs")
    protected DeviceInstanceT.ComObjectInstanceRefs comObjectInstanceRefs;
    @XmlElement(name = "ChannelInstances")
    protected DeviceInstanceT.ChannelInstances channelInstances;
    @XmlElement(name = "ModuleInstances")
    protected DeviceInstanceT.ModuleInstances moduleInstances;
    @XmlElement(name = "GroupObjectTree")
    protected DeviceInstanceT.GroupObjectTree groupObjectTree;
    @XmlElement(name = "AdditionalAddresses")
    protected DeviceInstanceT.AdditionalAddresses additionalAddresses;
    @XmlElement(name = "BinaryData")
    protected DeviceInstanceT.BinaryDatas binaryData;
    @XmlElement(name = "IPConfig")
    protected IPConfigT ipConfig;
    @XmlElement(name = "Security")
    protected SecurityT security;
    @XmlElement(name = "BusInterfaces")
    protected DeviceInstanceT.BusInterfaces busInterfaces;
    @XmlElement(name = "RfFastAckSlots")
    protected DeviceInstanceT.RfFastAckSlots rfFastAckSlots;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "ProductRefId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String productRefId;
    @XmlAttribute(name = "Hardware2ProgramRefId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hardware2ProgramRefId;
    @XmlAttribute(name = "Address")
    protected Integer address;
    @XmlAttribute(name = "Comment")
    protected String comment;
    @XmlAttribute(name = "LastModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;
    @XmlAttribute(name = "LastDownload")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastDownload;
    @XmlAttribute(name = "LastUsedAPDULength")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer lastUsedAPDULength;
    @XmlAttribute(name = "ReadMaxAPDULength")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer readMaxAPDULength;
    @XmlAttribute(name = "ReadMaxRoutingAPDULength")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer readMaxRoutingAPDULength;
    @XmlAttribute(name = "InstallationHints")
    protected String installationHints;
    @XmlAttribute(name = "CompletionStatus")
    protected CompletionStatusT completionStatus;
    @XmlAttribute(name = "IndividualAddressLoaded")
    protected Boolean individualAddressLoaded;
    @XmlAttribute(name = "ApplicationProgramLoaded")
    protected Boolean applicationProgramLoaded;
    @XmlAttribute(name = "ParametersLoaded")
    protected Boolean parametersLoaded;
    @XmlAttribute(name = "CommunicationPartLoaded")
    protected Boolean communicationPartLoaded;
    @XmlAttribute(name = "MediumConfigLoaded")
    protected Boolean mediumConfigLoaded;
    @XmlAttribute(name = "LoadedImage")
    protected byte[] loadedImage;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "CheckSums")
    protected byte[] checkSums;
    @XmlAttribute(name = "DownloadCounter")
    @XmlSchemaType(name = "unsignedInt")
    protected Long downloadCounter;
    @XmlAttribute(name = "IsActivityCalculated")
    protected Boolean isActivityCalculated;
    @XmlAttribute(name = "Broken")
    protected Boolean broken;
    @XmlAttribute(name = "SerialNumber")
    protected byte[] serialNumber;
    @XmlAttribute(name = "UniqueId")
    protected String uniqueId;
    @XmlAttribute(name = "IsRFRetransmitter")
    protected Boolean isRFRetransmitter;
    @XmlAttribute(name = "Puid", required = true)
    protected int puid;
    @XmlAttribute(name = "Context")
    protected String context;

    /**
     * Gets the value of the parameterInstanceRefs property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.ParameterInstanceRefs }
     *     
     */
    public DeviceInstanceT.ParameterInstanceRefs getParameterInstanceRefs() {
        return parameterInstanceRefs;
    }

    /**
     * Sets the value of the parameterInstanceRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.ParameterInstanceRefs }
     *     
     */
    public void setParameterInstanceRefs(DeviceInstanceT.ParameterInstanceRefs value) {
        this.parameterInstanceRefs = value;
    }

    /**
     * Gets the value of the comObjectInstanceRefs property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.ComObjectInstanceRefs }
     *     
     */
    public DeviceInstanceT.ComObjectInstanceRefs getComObjectInstanceRefs() {
        return comObjectInstanceRefs;
    }

    /**
     * Sets the value of the comObjectInstanceRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.ComObjectInstanceRefs }
     *     
     */
    public void setComObjectInstanceRefs(DeviceInstanceT.ComObjectInstanceRefs value) {
        this.comObjectInstanceRefs = value;
    }

    /**
     * Gets the value of the channelInstances property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.ChannelInstances }
     *     
     */
    public DeviceInstanceT.ChannelInstances getChannelInstances() {
        return channelInstances;
    }

    /**
     * Sets the value of the channelInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.ChannelInstances }
     *     
     */
    public void setChannelInstances(DeviceInstanceT.ChannelInstances value) {
        this.channelInstances = value;
    }

    /**
     * Gets the value of the moduleInstances property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.ModuleInstances }
     *     
     */
    public DeviceInstanceT.ModuleInstances getModuleInstances() {
        return moduleInstances;
    }

    /**
     * Sets the value of the moduleInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.ModuleInstances }
     *     
     */
    public void setModuleInstances(DeviceInstanceT.ModuleInstances value) {
        this.moduleInstances = value;
    }

    /**
     * Gets the value of the groupObjectTree property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.GroupObjectTree }
     *     
     */
    public DeviceInstanceT.GroupObjectTree getGroupObjectTree() {
        return groupObjectTree;
    }

    /**
     * Sets the value of the groupObjectTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.GroupObjectTree }
     *     
     */
    public void setGroupObjectTree(DeviceInstanceT.GroupObjectTree value) {
        this.groupObjectTree = value;
    }

    /**
     * Gets the value of the additionalAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.AdditionalAddresses }
     *     
     */
    public DeviceInstanceT.AdditionalAddresses getAdditionalAddresses() {
        return additionalAddresses;
    }

    /**
     * Sets the value of the additionalAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.AdditionalAddresses }
     *     
     */
    public void setAdditionalAddresses(DeviceInstanceT.AdditionalAddresses value) {
        this.additionalAddresses = value;
    }

    /**
     * Gets the value of the binaryData property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.BinaryDatas }
     *     
     */
    public DeviceInstanceT.BinaryDatas getBinaryData() {
        return binaryData;
    }

    /**
     * Sets the value of the binaryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.BinaryDatas }
     *     
     */
    public void setBinaryData(DeviceInstanceT.BinaryDatas value) {
        this.binaryData = value;
    }

    /**
     * Gets the value of the ipConfig property.
     * 
     * @return
     *     possible object is
     *     {@link IPConfigT }
     *     
     */
    public IPConfigT getIPConfig() {
        return ipConfig;
    }

    /**
     * Sets the value of the ipConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPConfigT }
     *     
     */
    public void setIPConfig(IPConfigT value) {
        this.ipConfig = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityT }
     *     
     */
    public SecurityT getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityT }
     *     
     */
    public void setSecurity(SecurityT value) {
        this.security = value;
    }

    /**
     * Gets the value of the busInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.BusInterfaces }
     *     
     */
    public DeviceInstanceT.BusInterfaces getBusInterfaces() {
        return busInterfaces;
    }

    /**
     * Sets the value of the busInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.BusInterfaces }
     *     
     */
    public void setBusInterfaces(DeviceInstanceT.BusInterfaces value) {
        this.busInterfaces = value;
    }

    /**
     * Gets the value of the rfFastAckSlots property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceInstanceT.RfFastAckSlots }
     *     
     */
    public DeviceInstanceT.RfFastAckSlots getRfFastAckSlots() {
        return rfFastAckSlots;
    }

    /**
     * Sets the value of the rfFastAckSlots property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceInstanceT.RfFastAckSlots }
     *     
     */
    public void setRfFastAckSlots(DeviceInstanceT.RfFastAckSlots value) {
        this.rfFastAckSlots = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the productRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductRefId() {
        return productRefId;
    }

    /**
     * Sets the value of the productRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductRefId(String value) {
        this.productRefId = value;
    }

    /**
     * Gets the value of the hardware2ProgramRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardware2ProgramRefId() {
        return hardware2ProgramRefId;
    }

    /**
     * Sets the value of the hardware2ProgramRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardware2ProgramRefId(String value) {
        this.hardware2ProgramRefId = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAddress(Integer value) {
        this.address = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the lastDownload property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDownload() {
        return lastDownload;
    }

    /**
     * Sets the value of the lastDownload property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDownload(XMLGregorianCalendar value) {
        this.lastDownload = value;
    }

    /**
     * Gets the value of the lastUsedAPDULength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastUsedAPDULength() {
        return lastUsedAPDULength;
    }

    /**
     * Sets the value of the lastUsedAPDULength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastUsedAPDULength(Integer value) {
        this.lastUsedAPDULength = value;
    }

    /**
     * Gets the value of the readMaxAPDULength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReadMaxAPDULength() {
        return readMaxAPDULength;
    }

    /**
     * Sets the value of the readMaxAPDULength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReadMaxAPDULength(Integer value) {
        this.readMaxAPDULength = value;
    }

    /**
     * Gets the value of the readMaxRoutingAPDULength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReadMaxRoutingAPDULength() {
        return readMaxRoutingAPDULength;
    }

    /**
     * Sets the value of the readMaxRoutingAPDULength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReadMaxRoutingAPDULength(Integer value) {
        this.readMaxRoutingAPDULength = value;
    }

    /**
     * Gets the value of the installationHints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallationHints() {
        return installationHints;
    }

    /**
     * Sets the value of the installationHints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallationHints(String value) {
        this.installationHints = value;
    }

    /**
     * Gets the value of the completionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CompletionStatusT }
     *     
     */
    public CompletionStatusT getCompletionStatus() {
        if (completionStatus == null) {
            return CompletionStatusT.UNDEFINED;
        } else {
            return completionStatus;
        }
    }

    /**
     * Sets the value of the completionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompletionStatusT }
     *     
     */
    public void setCompletionStatus(CompletionStatusT value) {
        this.completionStatus = value;
    }

    /**
     * Gets the value of the individualAddressLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIndividualAddressLoaded() {
        if (individualAddressLoaded == null) {
            return false;
        } else {
            return individualAddressLoaded;
        }
    }

    /**
     * Sets the value of the individualAddressLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndividualAddressLoaded(Boolean value) {
        this.individualAddressLoaded = value;
    }

    /**
     * Gets the value of the applicationProgramLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isApplicationProgramLoaded() {
        if (applicationProgramLoaded == null) {
            return false;
        } else {
            return applicationProgramLoaded;
        }
    }

    /**
     * Sets the value of the applicationProgramLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplicationProgramLoaded(Boolean value) {
        this.applicationProgramLoaded = value;
    }

    /**
     * Gets the value of the parametersLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isParametersLoaded() {
        if (parametersLoaded == null) {
            return false;
        } else {
            return parametersLoaded;
        }
    }

    /**
     * Sets the value of the parametersLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setParametersLoaded(Boolean value) {
        this.parametersLoaded = value;
    }

    /**
     * Gets the value of the communicationPartLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCommunicationPartLoaded() {
        if (communicationPartLoaded == null) {
            return false;
        } else {
            return communicationPartLoaded;
        }
    }

    /**
     * Sets the value of the communicationPartLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommunicationPartLoaded(Boolean value) {
        this.communicationPartLoaded = value;
    }

    /**
     * Gets the value of the mediumConfigLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMediumConfigLoaded() {
        if (mediumConfigLoaded == null) {
            return false;
        } else {
            return mediumConfigLoaded;
        }
    }

    /**
     * Sets the value of the mediumConfigLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMediumConfigLoaded(Boolean value) {
        this.mediumConfigLoaded = value;
    }

    /**
     * Gets the value of the loadedImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLoadedImage() {
        return loadedImage;
    }

    /**
     * Sets the value of the loadedImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLoadedImage(byte[] value) {
        this.loadedImage = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the checkSums property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCheckSums() {
        return checkSums;
    }

    /**
     * Sets the value of the checkSums property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCheckSums(byte[] value) {
        this.checkSums = value;
    }

    /**
     * Gets the value of the downloadCounter property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDownloadCounter() {
        return downloadCounter;
    }

    /**
     * Sets the value of the downloadCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDownloadCounter(Long value) {
        this.downloadCounter = value;
    }

    /**
     * Gets the value of the isActivityCalculated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsActivityCalculated() {
        return isActivityCalculated;
    }

    /**
     * Sets the value of the isActivityCalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActivityCalculated(Boolean value) {
        this.isActivityCalculated = value;
    }

    /**
     * Gets the value of the broken property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBroken() {
        if (broken == null) {
            return false;
        } else {
            return broken;
        }
    }

    /**
     * Sets the value of the broken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBroken(Boolean value) {
        this.broken = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSerialNumber(byte[] value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueId(String value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the isRFRetransmitter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsRFRetransmitter() {
        if (isRFRetransmitter == null) {
            return false;
        } else {
            return isRFRetransmitter;
        }
    }

    /**
     * Sets the value of the isRFRetransmitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRFRetransmitter(Boolean value) {
        this.isRFRetransmitter = value;
    }

    /**
     * Gets the value of the puid property.
     * 
     */
    public int getPuid() {
        return puid;
    }

    /**
     * Sets the value of the puid property.
     * 
     */
    public void setPuid(int value) {
        this.puid = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Address" maxOccurs="254">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Address" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
     *                       &lt;minInclusive value="1"/>
     *                       &lt;maxInclusive value="255"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
     *                 &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address"
    })
    public static class AdditionalAddresses {

        @XmlElement(name = "Address", required = true)
        protected List<DeviceInstanceT.AdditionalAddresses.Address> address;

        /**
         * Gets the value of the address property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the address property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeviceInstanceT.AdditionalAddresses.Address }
         * 
         * 
         */
        public List<DeviceInstanceT.AdditionalAddresses.Address> getAddress() {
            if (address == null) {
                address = new ArrayList<DeviceInstanceT.AdditionalAddresses.Address>();
            }
            return this.address;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Address" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
         *             &lt;minInclusive value="1"/>
         *             &lt;maxInclusive value="255"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
         *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Address {

            @XmlAttribute(name = "Address", required = true)
            protected short address;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Description")
            protected String description;
            @XmlAttribute(name = "Comment")
            protected String comment;

            /**
             * Gets the value of the address property.
             * 
             */
            public short getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             */
            public void setAddress(short value) {
                this.address = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComment(String value) {
                this.comment = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BinaryData" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="RefId" type="{http://knx.org/xml/project/20}IDREF" />
     *                 &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
     *                 &lt;attribute name="AutoCopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "binaryData"
    })
    public static class BinaryDatas {

        @XmlElement(name = "BinaryData", required = true)
        protected List<DeviceInstanceT.BinaryDatas.BinaryData> binaryData;

        /**
         * Gets the value of the binaryData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the binaryData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBinaryData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeviceInstanceT.BinaryDatas.BinaryData }
         * 
         * 
         */
        public List<DeviceInstanceT.BinaryDatas.BinaryData> getBinaryData() {
            if (binaryData == null) {
                binaryData = new ArrayList<DeviceInstanceT.BinaryDatas.BinaryData>();
            }
            return this.binaryData;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="RefId" type="{http://knx.org/xml/project/20}IDREF" />
         *       &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
         *       &lt;attribute name="AutoCopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "data"
        })
        public static class BinaryData {

            @XmlElement(name = "Data")
            protected byte[] data;
            @XmlAttribute(name = "Id")
            protected String id;
            @XmlAttribute(name = "RefId")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String refId;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "AutoCopy")
            protected Boolean autoCopy;

            /**
             * Gets the value of the data property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getData() {
                return data;
            }

            /**
             * Sets the value of the data property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setData(byte[] value) {
                this.data = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the refId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefId() {
                return refId;
            }

            /**
             * Sets the value of the refId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefId(String value) {
                this.refId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the autoCopy property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isAutoCopy() {
                if (autoCopy == null) {
                    return false;
                } else {
                    return autoCopy;
                }
            }

            /**
             * Sets the value of the autoCopy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAutoCopy(Boolean value) {
                this.autoCopy = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BusInterface" type="{http://knx.org/xml/project/20}BusInterface_t" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "busInterface"
    })
    public static class BusInterfaces {

        @XmlElement(name = "BusInterface", required = true)
        protected List<BusInterfaceT> busInterface;

        /**
         * Gets the value of the busInterface property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the busInterface property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBusInterface().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusInterfaceT }
         * 
         * 
         */
        public List<BusInterfaceT> getBusInterface() {
            if (busInterface == null) {
                busInterface = new ArrayList<BusInterfaceT>();
            }
            return this.busInterface;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ChannelInstance" type="{http://knx.org/xml/project/20}ChannelInstance_t" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "channelInstance"
    })
    public static class ChannelInstances {

        @XmlElement(name = "ChannelInstance", required = true)
        protected List<ChannelInstanceT> channelInstance;

        /**
         * Gets the value of the channelInstance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the channelInstance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChannelInstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChannelInstanceT }
         * 
         * 
         */
        public List<ChannelInstanceT> getChannelInstance() {
            if (channelInstance == null) {
                channelInstance = new ArrayList<ChannelInstanceT>();
            }
            return this.channelInstance;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ComObjectInstanceRef" type="{http://knx.org/xml/project/20}ComObjectInstanceRef_t" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comObjectInstanceRef"
    })
    public static class ComObjectInstanceRefs {

        @XmlElement(name = "ComObjectInstanceRef", required = true)
        protected List<ComObjectInstanceRefT> comObjectInstanceRef;

        /**
         * Gets the value of the comObjectInstanceRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comObjectInstanceRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComObjectInstanceRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ComObjectInstanceRefT }
         * 
         * 
         */
        public List<ComObjectInstanceRefT> getComObjectInstanceRef() {
            if (comObjectInstanceRef == null) {
                comObjectInstanceRef = new ArrayList<ComObjectInstanceRefT>();
            }
            return this.comObjectInstanceRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nodes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Node" type="{http://knx.org/xml/project/20}Node_t" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="GroupObjectInstances" type="{http://knx.org/xml/project/20}RELIDREFS" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nodes"
    })
    public static class GroupObjectTree {

        @XmlElement(name = "Nodes")
        protected DeviceInstanceT.GroupObjectTree.Nodes nodes;
        @XmlAttribute(name = "GroupObjectInstances")
        protected List<String> groupObjectInstances;

        /**
         * Gets the value of the nodes property.
         * 
         * @return
         *     possible object is
         *     {@link DeviceInstanceT.GroupObjectTree.Nodes }
         *     
         */
        public DeviceInstanceT.GroupObjectTree.Nodes getNodes() {
            return nodes;
        }

        /**
         * Sets the value of the nodes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeviceInstanceT.GroupObjectTree.Nodes }
         *     
         */
        public void setNodes(DeviceInstanceT.GroupObjectTree.Nodes value) {
            this.nodes = value;
        }

        /**
         * Gets the value of the groupObjectInstances property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupObjectInstances property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroupObjectInstances().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGroupObjectInstances() {
            if (groupObjectInstances == null) {
                groupObjectInstances = new ArrayList<String>();
            }
            return this.groupObjectInstances;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Node" type="{http://knx.org/xml/project/20}Node_t" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "node"
        })
        public static class Nodes {

            @XmlElement(name = "Node", required = true)
            protected List<NodeT> node;

            /**
             * Gets the value of the node property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the node property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getNode().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NodeT }
             * 
             * 
             */
            public List<NodeT> getNode() {
                if (node == null) {
                    node = new ArrayList<NodeT>();
                }
                return this.node;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ModuleInstance" type="{http://knx.org/xml/project/20}ModuleInstance_t" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "moduleInstance"
    })
    public static class ModuleInstances {

        @XmlElement(name = "ModuleInstance", required = true)
        protected List<ModuleInstanceT> moduleInstance;

        /**
         * Gets the value of the moduleInstance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the moduleInstance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModuleInstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ModuleInstanceT }
         * 
         * 
         */
        public List<ModuleInstanceT> getModuleInstance() {
            if (moduleInstance == null) {
                moduleInstance = new ArrayList<ModuleInstanceT>();
            }
            return this.moduleInstance;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ParameterInstanceRef" type="{http://knx.org/xml/project/20}ParameterInstanceRef_t" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameterInstanceRef"
    })
    public static class ParameterInstanceRefs {

        @XmlElement(name = "ParameterInstanceRef", required = true)
        protected List<ParameterInstanceRefT> parameterInstanceRef;

        /**
         * Gets the value of the parameterInstanceRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameterInstanceRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameterInstanceRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParameterInstanceRefT }
         * 
         * 
         */
        public List<ParameterInstanceRefT> getParameterInstanceRef() {
            if (parameterInstanceRef == null) {
                parameterInstanceRef = new ArrayList<ParameterInstanceRefT>();
            }
            return this.parameterInstanceRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Slot" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="GroupAddressRefId" use="required" type="{http://knx.org/xml/project/20}IDREF" />
     *                 &lt;attribute name="Number" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
     *                       &lt;maxInclusive value="63"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "slot"
    })
    public static class RfFastAckSlots {

        @XmlElement(name = "Slot", required = true)
        protected List<DeviceInstanceT.RfFastAckSlots.Slot> slot;

        /**
         * Gets the value of the slot property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the slot property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSlot().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeviceInstanceT.RfFastAckSlots.Slot }
         * 
         * 
         */
        public List<DeviceInstanceT.RfFastAckSlots.Slot> getSlot() {
            if (slot == null) {
                slot = new ArrayList<DeviceInstanceT.RfFastAckSlots.Slot>();
            }
            return this.slot;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="GroupAddressRefId" use="required" type="{http://knx.org/xml/project/20}IDREF" />
         *       &lt;attribute name="Number" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
         *             &lt;maxInclusive value="63"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Slot {

            @XmlAttribute(name = "GroupAddressRefId", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String groupAddressRefId;
            @XmlAttribute(name = "Number", required = true)
            protected short number;

            /**
             * Gets the value of the groupAddressRefId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGroupAddressRefId() {
                return groupAddressRefId;
            }

            /**
             * Sets the value of the groupAddressRefId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGroupAddressRefId(String value) {
                this.groupAddressRefId = value;
            }

            /**
             * Gets the value of the number property.
             * 
             */
            public short getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             */
            public void setNumber(short value) {
                this.number = value;
            }

        }

    }

}
