//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceCertificate_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceCertificate_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SerialNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="FDSK" use="required" type="{http://knx.org/xml/project/20}Aes128Key_t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceCertificate_t")
public class DeviceCertificateT {

    @XmlAttribute(name = "SerialNumber", required = true)
    protected byte[] serialNumber;
    @XmlAttribute(name = "FDSK", required = true)
    protected String fdsk;

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSerialNumber(byte[] value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the fdsk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFDSK() {
        return fdsk;
    }

    /**
     * Sets the value of the fdsk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFDSK(String value) {
        this.fdsk = value;
    }

}
