//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Fixup_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fixup_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Offset" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;maxInclusive value="65535"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="FunctionRef" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="CodeSegment" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fixup_t", propOrder = {
    "offset"
})
public class FixupT {

    @XmlElement(name = "Offset", type = Long.class)
    protected List<Long> offset;
    @XmlAttribute(name = "FunctionRef", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String functionRef;
    @XmlAttribute(name = "CodeSegment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String codeSegment;

    /**
     * Gets the value of the offset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getOffset() {
        if (offset == null) {
            offset = new ArrayList<Long>();
        }
        return this.offset;
    }

    /**
     * Gets the value of the functionRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionRef() {
        return functionRef;
    }

    /**
     * Sets the value of the functionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionRef(String value) {
        this.functionRef = value;
    }

    /**
     * Gets the value of the codeSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSegment() {
        return codeSegment;
    }

    /**
     * Sets the value of the codeSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSegment(String value) {
        this.codeSegment = value;
    }

}
