//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupAddressStyle_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GroupAddressStyle_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TwoLevel"/>
 *     &lt;enumeration value="ThreeLevel"/>
 *     &lt;enumeration value="Free"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GroupAddressStyle_t")
@XmlEnum
public enum GroupAddressStyleT {

    @XmlEnumValue("TwoLevel")
    TWO_LEVEL("TwoLevel"),
    @XmlEnumValue("ThreeLevel")
    THREE_LEVEL("ThreeLevel"),
    @XmlEnumValue("Free")
    FREE("Free");
    private final String value;

    GroupAddressStyleT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupAddressStyleT fromValue(String v) {
        for (GroupAddressStyleT c: GroupAddressStyleT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
