//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//

package lu.berscheid.knx.generator.model;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "masterData", "manufacturerData", "project" })
@XmlRootElement(name = "KNX")
@Data
public class KNX {
	@XmlElement(name = "MasterData")
	protected MasterDataT masterData;

	@XmlElement(name = "ManufacturerData")
	protected ManufacturerDataT manufacturerData;

	@XmlElement(name = "Project")
	protected List<ProjectT> project;

	@XmlAttribute(name = "CreatedBy")
	protected String createdBy;

	@XmlAttribute(name = "ToolVersion")
	protected String toolVersion;
}
