//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdCtrlDeclarePropDesc_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdCtrlDeclarePropDesc_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://knx.org/xml/project/20}LdCtrlBase_t">
 *       &lt;attribute name="ObjIdx" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="ObjType" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="Occurrence" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="0" />
 *       &lt;attribute name="PropId" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="PropType" use="required" type="{http://knx.org/xml/project/20}PropType_t" />
 *       &lt;attribute name="MaxElements" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ReadAccess" use="required" type="{http://knx.org/xml/project/20}AccessLevel_t" />
 *       &lt;attribute name="WriteAccess" use="required" type="{http://knx.org/xml/project/20}AccessLevel_t" />
 *       &lt;attribute name="Writable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdCtrlDeclarePropDesc_t")
public class LdCtrlDeclarePropDescT
    extends LdCtrlBaseT
{

    @XmlAttribute(name = "ObjIdx")
    @XmlSchemaType(name = "unsignedByte")
    protected Short objIdx;
    @XmlAttribute(name = "ObjType")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer objType;
    @XmlAttribute(name = "Occurrence")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer occurrence;
    @XmlAttribute(name = "PropId", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int propId;
    @XmlAttribute(name = "PropType", required = true)
    protected PropTypeT propType;
    @XmlAttribute(name = "MaxElements", required = true)
    protected int maxElements;
    @XmlAttribute(name = "ReadAccess", required = true)
    protected short readAccess;
    @XmlAttribute(name = "WriteAccess", required = true)
    protected short writeAccess;
    @XmlAttribute(name = "Writable", required = true)
    protected boolean writable;

    /**
     * Gets the value of the objIdx property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getObjIdx() {
        return objIdx;
    }

    /**
     * Sets the value of the objIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setObjIdx(Short value) {
        this.objIdx = value;
    }

    /**
     * Gets the value of the objType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObjType() {
        return objType;
    }

    /**
     * Sets the value of the objType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObjType(Integer value) {
        this.objType = value;
    }

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getOccurrence() {
        if (occurrence == null) {
            return  0;
        } else {
            return occurrence;
        }
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOccurrence(Integer value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the propId property.
     * 
     */
    public int getPropId() {
        return propId;
    }

    /**
     * Sets the value of the propId property.
     * 
     */
    public void setPropId(int value) {
        this.propId = value;
    }

    /**
     * Gets the value of the propType property.
     * 
     * @return
     *     possible object is
     *     {@link PropTypeT }
     *     
     */
    public PropTypeT getPropType() {
        return propType;
    }

    /**
     * Sets the value of the propType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropTypeT }
     *     
     */
    public void setPropType(PropTypeT value) {
        this.propType = value;
    }

    /**
     * Gets the value of the maxElements property.
     * 
     */
    public int getMaxElements() {
        return maxElements;
    }

    /**
     * Sets the value of the maxElements property.
     * 
     */
    public void setMaxElements(int value) {
        this.maxElements = value;
    }

    /**
     * Gets the value of the readAccess property.
     * 
     */
    public short getReadAccess() {
        return readAccess;
    }

    /**
     * Sets the value of the readAccess property.
     * 
     */
    public void setReadAccess(short value) {
        this.readAccess = value;
    }

    /**
     * Gets the value of the writeAccess property.
     * 
     */
    public short getWriteAccess() {
        return writeAccess;
    }

    /**
     * Sets the value of the writeAccess property.
     * 
     */
    public void setWriteAccess(short value) {
        this.writeAccess = value;
    }

    /**
     * Gets the value of the writable property.
     * 
     */
    public boolean isWritable() {
        return writable;
    }

    /**
     * Sets the value of the writable property.
     * 
     */
    public void setWritable(boolean value) {
        this.writable = value;
    }

}
