//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for LdCtrlProgressText_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdCtrlProgressText_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://knx.org/xml/project/20}LdCtrlBase_t">
 *       &lt;attribute name="TextId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="MessageRef" type="{http://knx.org/xml/project/20}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdCtrlProgressText_t")
public class LdCtrlProgressTextT
    extends LdCtrlBaseT
{

    @XmlAttribute(name = "TextId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long textId;
    @XmlAttribute(name = "MessageRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageRef;

    /**
     * Gets the value of the textId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * Sets the value of the textId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTextId(Long value) {
        this.textId = value;
    }

    /**
     * Gets the value of the messageRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageRef() {
        return messageRef;
    }

    /**
     * Sets the value of the messageRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageRef(String value) {
        this.messageRef = value;
    }

}
