//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdCtrlMemAddrSpace_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LdCtrlMemAddrSpace_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Standard"/>
 *     &lt;enumeration value="User"/>
 *     &lt;enumeration value="LcSlave"/>
 *     &lt;enumeration value="LcFilter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LdCtrlMemAddrSpace_t")
@XmlEnum
public enum LdCtrlMemAddrSpaceT {

    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    @XmlEnumValue("User")
    USER("User"),
    @XmlEnumValue("LcSlave")
    LC_SLAVE("LcSlave"),
    @XmlEnumValue("LcFilter")
    LC_FILTER("LcFilter");
    private final String value;

    LdCtrlMemAddrSpaceT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LdCtrlMemAddrSpaceT fromValue(String v) {
        for (LdCtrlMemAddrSpaceT c: LdCtrlMemAddrSpaceT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
