//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdCtrlProcType_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LdCtrlProcType_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="full"/>
 *     &lt;enumeration value="par"/>
 *     &lt;enumeration value="grp"/>
 *     &lt;enumeration value="full,par"/>
 *     &lt;enumeration value="full,grp"/>
 *     &lt;enumeration value="par,grp"/>
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="auto"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LdCtrlProcType_t")
@XmlEnum
public enum LdCtrlProcTypeT {

    @XmlEnumValue("full")
    FULL("full"),
    @XmlEnumValue("par")
    PAR("par"),
    @XmlEnumValue("grp")
    GRP("grp"),
    @XmlEnumValue("full,par")
    FULL_PAR("full,par"),
    @XmlEnumValue("full,grp")
    FULL_GRP("full,grp"),
    @XmlEnumValue("par,grp")
    PAR_GRP("par,grp"),
    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("auto")
    AUTO("auto");
    private final String value;

    LdCtrlProcTypeT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LdCtrlProcTypeT fromValue(String v) {
        for (LdCtrlProcTypeT c: LdCtrlProcTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
