//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdCtrlLoadImageMem_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdCtrlLoadImageMem_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://knx.org/xml/project/20}LdCtrlBase_t">
 *       &lt;attribute name="AddressSpace" type="{http://knx.org/xml/project/20}LdCtrlMemAddrSpace_t" default="Standard" />
 *       &lt;attribute name="Address" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="Size" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdCtrlLoadImageMem_t")
public class LdCtrlLoadImageMemT
    extends LdCtrlBaseT
{

    @XmlAttribute(name = "AddressSpace")
    protected LdCtrlMemAddrSpaceT addressSpace;
    @XmlAttribute(name = "Address", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long address;
    @XmlAttribute(name = "Size", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long size;

    /**
     * Gets the value of the addressSpace property.
     * 
     * @return
     *     possible object is
     *     {@link LdCtrlMemAddrSpaceT }
     *     
     */
    public LdCtrlMemAddrSpaceT getAddressSpace() {
        if (addressSpace == null) {
            return LdCtrlMemAddrSpaceT.STANDARD;
        } else {
            return addressSpace;
        }
    }

    /**
     * Sets the value of the addressSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdCtrlMemAddrSpaceT }
     *     
     */
    public void setAddressSpace(LdCtrlMemAddrSpaceT value) {
        this.addressSpace = value;
    }

    /**
     * Gets the value of the address property.
     * 
     */
    public long getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     */
    public void setAddress(long value) {
        this.address = value;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(long value) {
        this.size = value;
    }

}
