//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdCtrlTaskPtr_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdCtrlTaskPtr_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://knx.org/xml/project/20}LdCtrlBase_t">
 *       &lt;attribute name="LsmIdx" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="ObjType" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="Occurrence" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="0" />
 *       &lt;attribute name="InitPtr" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="SavePtr" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="SerialPtr" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdCtrlTaskPtr_t")
public class LdCtrlTaskPtrT
    extends LdCtrlBaseT
{

    @XmlAttribute(name = "LsmIdx")
    @XmlSchemaType(name = "unsignedByte")
    protected Short lsmIdx;
    @XmlAttribute(name = "ObjType")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer objType;
    @XmlAttribute(name = "Occurrence")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer occurrence;
    @XmlAttribute(name = "InitPtr", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int initPtr;
    @XmlAttribute(name = "SavePtr", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int savePtr;
    @XmlAttribute(name = "SerialPtr", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int serialPtr;

    /**
     * Gets the value of the lsmIdx property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getLsmIdx() {
        return lsmIdx;
    }

    /**
     * Sets the value of the lsmIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setLsmIdx(Short value) {
        this.lsmIdx = value;
    }

    /**
     * Gets the value of the objType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObjType() {
        return objType;
    }

    /**
     * Sets the value of the objType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObjType(Integer value) {
        this.objType = value;
    }

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getOccurrence() {
        if (occurrence == null) {
            return  0;
        } else {
            return occurrence;
        }
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOccurrence(Integer value) {
        this.occurrence = value;
    }

    /**
     * Gets the value of the initPtr property.
     * 
     */
    public int getInitPtr() {
        return initPtr;
    }

    /**
     * Sets the value of the initPtr property.
     * 
     */
    public void setInitPtr(int value) {
        this.initPtr = value;
    }

    /**
     * Gets the value of the savePtr property.
     * 
     */
    public int getSavePtr() {
        return savePtr;
    }

    /**
     * Sets the value of the savePtr property.
     * 
     */
    public void setSavePtr(int value) {
        this.savePtr = value;
    }

    /**
     * Gets the value of the serialPtr property.
     * 
     */
    public int getSerialPtr() {
        return serialPtr;
    }

    /**
     * Sets the value of the serialPtr property.
     * 
     */
    public void setSerialPtr(int value) {
        this.serialPtr = value;
    }

}
