//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MemoryUnion_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemoryUnion_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CodeSegment" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="Offset" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *             &lt;maxInclusive value="1048575"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="BitOffset" use="required" type="{http://knx.org/xml/project/20}BitOffset_t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemoryUnion_t")
@XmlSeeAlso({
    lu.berscheid.knx.generator.model.ModuleDefStaticT.Parameters.Union.Memory.class
})
public class MemoryUnionT {

    @XmlAttribute(name = "CodeSegment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String codeSegment;
    @XmlAttribute(name = "Offset", required = true)
    protected long offset;
    @XmlAttribute(name = "BitOffset", required = true)
    protected short bitOffset;

    /**
     * Gets the value of the codeSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSegment() {
        return codeSegment;
    }

    /**
     * Sets the value of the codeSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSegment(String value) {
        this.codeSegment = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public long getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(long value) {
        this.offset = value;
    }

    /**
     * Gets the value of the bitOffset property.
     * 
     */
    public short getBitOffset() {
        return bitOffset;
    }

    /**
     * Sets the value of the bitOffset property.
     * 
     */
    public void setBitOffset(short value) {
        this.bitOffset = value;
    }

}
