//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for P2PLinkBusInterfaceEndpoint_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="P2PLinkBusInterfaceEndpoint_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://knx.org/xml/project/20}P2PLinkEndpoint_t">
 *       &lt;attribute name="BusInterfaceRefId" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "P2PLinkBusInterfaceEndpoint_t")
public abstract class P2PLinkBusInterfaceEndpointT
    extends P2PLinkEndpointT
{

    @XmlAttribute(name = "BusInterfaceRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object busInterfaceRefId;

    /**
     * Gets the value of the busInterfaceRefId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBusInterfaceRefId() {
        return busInterfaceRefId;
    }

    /**
     * Sets the value of the busInterfaceRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBusInterfaceRefId(Object value) {
        this.busInterfaceRefId = value;
    }

}
