//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ParameterRef_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterRef_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="RefId" use="required" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="Name" type="{http://knx.org/xml/project/20}String255_t" />
 *       &lt;attribute name="Text" type="{http://knx.org/xml/project/20}LanguageDependentString255_t" />
 *       &lt;attribute name="SuffixText" type="{http://knx.org/xml/project/20}LanguageDependentString20_t" />
 *       &lt;attribute name="Tag" type="{http://knx.org/xml/project/20}String50_t" />
 *       &lt;attribute name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Access" type="{http://knx.org/xml/project/20}Access_t" />
 *       &lt;attribute name="Value" type="{http://knx.org/xml/project/20}Value_t" />
 *       &lt;attribute name="InitialValue" type="{http://knx.org/xml/project/20}LanguageDependentString_t" />
 *       &lt;attribute name="CustomerAdjustable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="TextParameterRefId" type="{http://knx.org/xml/project/20}IDREF" />
 *       &lt;attribute name="InternalDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ForbidGrantingUseByCustomer" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Semantics" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterRef_t")
public class ParameterRefT {

    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "RefId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refId;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Text")
    protected String text;
    @XmlAttribute(name = "SuffixText")
    protected String suffixText;
    @XmlAttribute(name = "Tag")
    protected String tag;
    @XmlAttribute(name = "DisplayOrder")
    protected Integer displayOrder;
    @XmlAttribute(name = "Access")
    protected AccessT access;
    @XmlAttribute(name = "Value")
    protected String value;
    @XmlAttribute(name = "InitialValue")
    protected String initialValue;
    @XmlAttribute(name = "CustomerAdjustable")
    protected Boolean customerAdjustable;
    @XmlAttribute(name = "TextParameterRefId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textParameterRefId;
    @XmlAttribute(name = "InternalDescription")
    protected String internalDescription;
    @XmlAttribute(name = "ForbidGrantingUseByCustomer")
    protected Boolean forbidGrantingUseByCustomer;
    @XmlAttribute(name = "Semantics")
    protected String semantics;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the suffixText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffixText() {
        return suffixText;
    }

    /**
     * Sets the value of the suffixText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffixText(String value) {
        this.suffixText = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisplayOrder(Integer value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link AccessT }
     *     
     */
    public AccessT getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessT }
     *     
     */
    public void setAccess(AccessT value) {
        this.access = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialValue(String value) {
        this.initialValue = value;
    }

    /**
     * Gets the value of the customerAdjustable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomerAdjustable() {
        return customerAdjustable;
    }

    /**
     * Sets the value of the customerAdjustable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomerAdjustable(Boolean value) {
        this.customerAdjustable = value;
    }

    /**
     * Gets the value of the textParameterRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextParameterRefId() {
        return textParameterRefId;
    }

    /**
     * Sets the value of the textParameterRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextParameterRefId(String value) {
        this.textParameterRefId = value;
    }

    /**
     * Gets the value of the internalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalDescription() {
        return internalDescription;
    }

    /**
     * Sets the value of the internalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalDescription(String value) {
        this.internalDescription = value;
    }

    /**
     * Gets the value of the forbidGrantingUseByCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isForbidGrantingUseByCustomer() {
        if (forbidGrantingUseByCustomer == null) {
            return false;
        } else {
            return forbidGrantingUseByCustomer;
        }
    }

    /**
     * Sets the value of the forbidGrantingUseByCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForbidGrantingUseByCustomer(Boolean value) {
        this.forbidGrantingUseByCustomer = value;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemantics() {
        return semantics;
    }

    /**
     * Sets the value of the semantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemantics(String value) {
        this.semantics = value;
    }

}
