//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropType_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropType_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PDT_CONTROL"/>
 *     &lt;enumeration value="PDT_CHAR"/>
 *     &lt;enumeration value="PDT_UNSIGNED_CHAR"/>
 *     &lt;enumeration value="PDT_INT"/>
 *     &lt;enumeration value="PDT_UNSIGNED_INT"/>
 *     &lt;enumeration value="PDT_KNX_FLOAT"/>
 *     &lt;enumeration value="PDT_DATE"/>
 *     &lt;enumeration value="PDT_TIME"/>
 *     &lt;enumeration value="PDT_LONG"/>
 *     &lt;enumeration value="PDT_UNSIGNED_LONG"/>
 *     &lt;enumeration value="PDT_FLOAT"/>
 *     &lt;enumeration value="PDT_DOUBLE"/>
 *     &lt;enumeration value="PDT_CHAR_BLOCK"/>
 *     &lt;enumeration value="PDT_POLL_GROUP_SETTINGS"/>
 *     &lt;enumeration value="PDT_SHORT_CHAR_BLOCK"/>
 *     &lt;enumeration value="PDT_DATE_TIME"/>
 *     &lt;enumeration value="PDT_VARIABLE_LENGTH"/>
 *     &lt;enumeration value="PDT_GENERIC_01"/>
 *     &lt;enumeration value="PDT_GENERIC_02"/>
 *     &lt;enumeration value="PDT_GENERIC_03"/>
 *     &lt;enumeration value="PDT_GENERIC_04"/>
 *     &lt;enumeration value="PDT_GENERIC_05"/>
 *     &lt;enumeration value="PDT_GENERIC_06"/>
 *     &lt;enumeration value="PDT_GENERIC_07"/>
 *     &lt;enumeration value="PDT_GENERIC_08"/>
 *     &lt;enumeration value="PDT_GENERIC_09"/>
 *     &lt;enumeration value="PDT_GENERIC_10"/>
 *     &lt;enumeration value="PDT_GENERIC_11"/>
 *     &lt;enumeration value="PDT_GENERIC_12"/>
 *     &lt;enumeration value="PDT_GENERIC_13"/>
 *     &lt;enumeration value="PDT_GENERIC_14"/>
 *     &lt;enumeration value="PDT_GENERIC_15"/>
 *     &lt;enumeration value="PDT_GENERIC_16"/>
 *     &lt;enumeration value="PDT_GENERIC_17"/>
 *     &lt;enumeration value="PDT_GENERIC_18"/>
 *     &lt;enumeration value="PDT_GENERIC_19"/>
 *     &lt;enumeration value="PDT_GENERIC_20"/>
 *     &lt;enumeration value="PDT_UTF-8"/>
 *     &lt;enumeration value="PDT_VERSION"/>
 *     &lt;enumeration value="PDT_ALARM_INFO"/>
 *     &lt;enumeration value="PDT_BINARY_INFORMATION"/>
 *     &lt;enumeration value="PDT_BITSET8"/>
 *     &lt;enumeration value="PDT_BITSET16"/>
 *     &lt;enumeration value="PDT_ENUM8"/>
 *     &lt;enumeration value="PDT_SCALING"/>
 *     &lt;enumeration value="PDT_NE_VL"/>
 *     &lt;enumeration value="PDT_NE_FL"/>
 *     &lt;enumeration value="PDT_FUNCTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PropType_t")
@XmlEnum
public enum PropTypeT {

    PDT_CONTROL("PDT_CONTROL"),
    PDT_CHAR("PDT_CHAR"),
    PDT_UNSIGNED_CHAR("PDT_UNSIGNED_CHAR"),
    PDT_INT("PDT_INT"),
    PDT_UNSIGNED_INT("PDT_UNSIGNED_INT"),
    PDT_KNX_FLOAT("PDT_KNX_FLOAT"),
    PDT_DATE("PDT_DATE"),
    PDT_TIME("PDT_TIME"),
    PDT_LONG("PDT_LONG"),
    PDT_UNSIGNED_LONG("PDT_UNSIGNED_LONG"),
    PDT_FLOAT("PDT_FLOAT"),
    PDT_DOUBLE("PDT_DOUBLE"),
    PDT_CHAR_BLOCK("PDT_CHAR_BLOCK"),
    PDT_POLL_GROUP_SETTINGS("PDT_POLL_GROUP_SETTINGS"),
    PDT_SHORT_CHAR_BLOCK("PDT_SHORT_CHAR_BLOCK"),
    PDT_DATE_TIME("PDT_DATE_TIME"),
    PDT_VARIABLE_LENGTH("PDT_VARIABLE_LENGTH"),
    PDT_GENERIC_01("PDT_GENERIC_01"),
    PDT_GENERIC_02("PDT_GENERIC_02"),
    PDT_GENERIC_03("PDT_GENERIC_03"),
    PDT_GENERIC_04("PDT_GENERIC_04"),
    PDT_GENERIC_05("PDT_GENERIC_05"),
    PDT_GENERIC_06("PDT_GENERIC_06"),
    PDT_GENERIC_07("PDT_GENERIC_07"),
    PDT_GENERIC_08("PDT_GENERIC_08"),
    PDT_GENERIC_09("PDT_GENERIC_09"),
    PDT_GENERIC_10("PDT_GENERIC_10"),
    PDT_GENERIC_11("PDT_GENERIC_11"),
    PDT_GENERIC_12("PDT_GENERIC_12"),
    PDT_GENERIC_13("PDT_GENERIC_13"),
    PDT_GENERIC_14("PDT_GENERIC_14"),
    PDT_GENERIC_15("PDT_GENERIC_15"),
    PDT_GENERIC_16("PDT_GENERIC_16"),
    PDT_GENERIC_17("PDT_GENERIC_17"),
    PDT_GENERIC_18("PDT_GENERIC_18"),
    PDT_GENERIC_19("PDT_GENERIC_19"),
    PDT_GENERIC_20("PDT_GENERIC_20"),
    @XmlEnumValue("PDT_UTF-8")
    PDT_UTF_8("PDT_UTF-8"),
    PDT_VERSION("PDT_VERSION"),
    PDT_ALARM_INFO("PDT_ALARM_INFO"),
    PDT_BINARY_INFORMATION("PDT_BINARY_INFORMATION"),
    @XmlEnumValue("PDT_BITSET8")
    PDT_BITSET_8("PDT_BITSET8"),
    @XmlEnumValue("PDT_BITSET16")
    PDT_BITSET_16("PDT_BITSET16"),
    @XmlEnumValue("PDT_ENUM8")
    PDT_ENUM_8("PDT_ENUM8"),
    PDT_SCALING("PDT_SCALING"),
    PDT_NE_VL("PDT_NE_VL"),
    PDT_NE_FL("PDT_NE_FL"),
    PDT_FUNCTION("PDT_FUNCTION");
    private final String value;

    PropTypeT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropTypeT fromValue(String v) {
        for (PropTypeT c: PropTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
