//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceAccess_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResourceAccess_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="remote"/>
 *     &lt;enumeration value="local1"/>
 *     &lt;enumeration value="local2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResourceAccess_t")
@XmlEnum
public enum ResourceAccessT {

    @XmlEnumValue("remote")
    REMOTE("remote"),
    @XmlEnumValue("local1")
    LOCAL_1("local1"),
    @XmlEnumValue("local2")
    LOCAL_2("local2");
    private final String value;

    ResourceAccessT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResourceAccessT fromValue(String v) {
        for (ResourceAccessT c: ResourceAccessT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
