//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 10:56:00 PM CEST 
//


package lu.berscheid.knx.generator.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Security_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Security_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="LoadedIPRoutingBackboneKey" type="{http://knx.org/xml/project/20}Aes128Key_t" />
 *       &lt;attribute name="DeviceAuthenticationCode" type="{http://knx.org/xml/project/20}String20_t" />
 *       &lt;attribute name="DeviceAuthenticationCodeHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="LoadedDeviceAuthenticationCodeHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="DeviceManagementPassword" type="{http://knx.org/xml/project/20}String20_t" />
 *       &lt;attribute name="DeviceManagementPasswordHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="LoadedDeviceManagementPasswordHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="ToolKey" type="{http://knx.org/xml/project/20}Aes128Key_t" />
 *       &lt;attribute name="LoadedToolKey" type="{http://knx.org/xml/project/20}Aes128Key_t" />
 *       &lt;attribute name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="SequenceNumberTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Security_t")
public class SecurityT {

    @XmlAttribute(name = "LoadedIPRoutingBackboneKey")
    protected String loadedIPRoutingBackboneKey;
    @XmlAttribute(name = "DeviceAuthenticationCode")
    protected String deviceAuthenticationCode;
    @XmlAttribute(name = "DeviceAuthenticationCodeHash")
    protected byte[] deviceAuthenticationCodeHash;
    @XmlAttribute(name = "LoadedDeviceAuthenticationCodeHash")
    protected byte[] loadedDeviceAuthenticationCodeHash;
    @XmlAttribute(name = "DeviceManagementPassword")
    protected String deviceManagementPassword;
    @XmlAttribute(name = "DeviceManagementPasswordHash")
    protected byte[] deviceManagementPasswordHash;
    @XmlAttribute(name = "LoadedDeviceManagementPasswordHash")
    protected byte[] loadedDeviceManagementPasswordHash;
    @XmlAttribute(name = "ToolKey")
    protected String toolKey;
    @XmlAttribute(name = "LoadedToolKey")
    protected String loadedToolKey;
    @XmlAttribute(name = "SequenceNumber")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger sequenceNumber;
    @XmlAttribute(name = "SequenceNumberTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sequenceNumberTimestamp;

    /**
     * Gets the value of the loadedIPRoutingBackboneKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadedIPRoutingBackboneKey() {
        return loadedIPRoutingBackboneKey;
    }

    /**
     * Sets the value of the loadedIPRoutingBackboneKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadedIPRoutingBackboneKey(String value) {
        this.loadedIPRoutingBackboneKey = value;
    }

    /**
     * Gets the value of the deviceAuthenticationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceAuthenticationCode() {
        return deviceAuthenticationCode;
    }

    /**
     * Sets the value of the deviceAuthenticationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceAuthenticationCode(String value) {
        this.deviceAuthenticationCode = value;
    }

    /**
     * Gets the value of the deviceAuthenticationCodeHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDeviceAuthenticationCodeHash() {
        return deviceAuthenticationCodeHash;
    }

    /**
     * Sets the value of the deviceAuthenticationCodeHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDeviceAuthenticationCodeHash(byte[] value) {
        this.deviceAuthenticationCodeHash = value;
    }

    /**
     * Gets the value of the loadedDeviceAuthenticationCodeHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLoadedDeviceAuthenticationCodeHash() {
        return loadedDeviceAuthenticationCodeHash;
    }

    /**
     * Sets the value of the loadedDeviceAuthenticationCodeHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLoadedDeviceAuthenticationCodeHash(byte[] value) {
        this.loadedDeviceAuthenticationCodeHash = value;
    }

    /**
     * Gets the value of the deviceManagementPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceManagementPassword() {
        return deviceManagementPassword;
    }

    /**
     * Sets the value of the deviceManagementPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceManagementPassword(String value) {
        this.deviceManagementPassword = value;
    }

    /**
     * Gets the value of the deviceManagementPasswordHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDeviceManagementPasswordHash() {
        return deviceManagementPasswordHash;
    }

    /**
     * Sets the value of the deviceManagementPasswordHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDeviceManagementPasswordHash(byte[] value) {
        this.deviceManagementPasswordHash = value;
    }

    /**
     * Gets the value of the loadedDeviceManagementPasswordHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLoadedDeviceManagementPasswordHash() {
        return loadedDeviceManagementPasswordHash;
    }

    /**
     * Sets the value of the loadedDeviceManagementPasswordHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLoadedDeviceManagementPasswordHash(byte[] value) {
        this.loadedDeviceManagementPasswordHash = value;
    }

    /**
     * Gets the value of the toolKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolKey() {
        return toolKey;
    }

    /**
     * Sets the value of the toolKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolKey(String value) {
        this.toolKey = value;
    }

    /**
     * Gets the value of the loadedToolKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadedToolKey() {
        return loadedToolKey;
    }

    /**
     * Sets the value of the loadedToolKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadedToolKey(String value) {
        this.loadedToolKey = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the sequenceNumberTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSequenceNumberTimestamp() {
        return sequenceNumberTimestamp;
    }

    /**
     * Sets the value of the sequenceNumberTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSequenceNumberTimestamp(XMLGregorianCalendar value) {
        this.sequenceNumberTimestamp = value;
    }

}
